In [ ]:
import numpy as np
a = np.array([[1,2], [3,4]])
b = a[ 1, 0]
print(b)
#here we used one of teh basic code to test slicing
#and giving the value to "b" from a using indexing method slicing

3


In [ ]:
import numpy as np
#we imported teh library

a = np.array([[5,6,7],[8,9,10]])
b = np.array ([[1,2,3],[4,5,6]])

#here we are going to use the arithematic operations on arrays using numpy
#and operators
print(a * b) #multiplcation
print(a + b) #adsition
print( a / b)#division
print(a - b) #subtraction

[[ 5 12 21]
 [32 45 60]]
[[ 6  8 10]
 [12 14 16]]
[[5.         3.         2.33333333]
 [2.         1.8        1.66666667]]
[[4 4 4]
 [4 4 4]]


In [ ]:
#now we are going write code for modifying array
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[ : 1, :2]
#my mistake was , thatif you want to modify an element in an array
#write the full range when slicing not just a[0,0] = b
#write b=a[ :1,:2] like this , then you can modify it
b[0,0] = 77

print(a[0,0])

77


Broadcasting is NumPy's way of automatically handling arrays of different shapes during arithmetic operations. Instead of writing loops, NumPy "stretches" smaller arrays to match larger ones.
Think of it like this: NumPy automatically repeats v for each row without actually copying the data in memory

In [ ]:
#y = x + v  # That's it! No loop needed!


#NumPy automatically "broadcasts" `v` across all rows of `x`:
#x = [[ 1,  2,  3],      v = [1, 0, 1]  (automatically repeated)
     #[ 4,  5,  6],          [1, 0, 1]
     #[ 7,  8,  9],    →     [1, 0, 1]
     #[10, 11, 12]]          [1, 0, 1]

Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


In [ ]:
import numpy as np

x = np.array([[1,2],[4,5,]]) #(2,2)
w = np.array([4,5]) #(3,)
w = np.reshape(w,(1,2))

#now we have to prepend (2,) to (1,3)
print (x.shape) #checking shape of x
print( w.shape) #checking shape of w
print( x+w)

(2, 2)
(1, 2)
[[ 5  7]
 [ 8 10]]


In [ ]:
#different broadcasting scenerios

import numpy as np

#by taking traspose , adding and taking transpose again
x = np.array([[1,2,3],[4,5,6,]])
w = np.array([4,5])
print((x.T + w).T)




[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
#different broadcasting scenerios

import numpy as np

#by reshaping the smaller array
x = np.array([[1,2,3],[4,5,6,]])
w = np.array([4,5])
print(x + np.reshape(w,(2,1)))




[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
#Create a 3D array (3x4x5), access specific elements using different slicing methods
#Perform element-wise operations (add, multiply, power)
#Use boolean indexing to filter arrays
#Reshape arrays and understand when it fails (shape compatibility)
#Broadcasting: add arrays of different shape

In [27]:
#creating a 3D array
import numpy as np

arr_3d = np.array([[[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20]],

                    [[21,22,23,24,25],
                     [26,27,28,29,30],
                     [31,32,33,34,35],
                     [36,37,38,39,40]],

                    [[41,42,43,44,45],
                     [46,47,48,49,50],
                     [51,52,53,54,55],
                     [56,57,58,59,60]]])

print("Shape:", arr_3d.shape)  # Should be (3, 4, 5)

# Now practice slicing:
# Get the first 2x2x2 block



arr_2 =arr_3d[ :2,:2 , :2]
print("the elementsin 2x2x2 array is:")
print(arr_2)

#last rows slicing
Last_rows = arr_3d[ : , 3, :]
print("The elements in ths last rows are :")
print(Last_rows)



## Get every other element in the last dimension
every_other_element = arr_3d[ : ,: , ::2]

print("the every other element is:")
print(every_other_element)



Shape: (3, 4, 5)
the elementsin 2x2x2 array is:
[[[ 1  2]
  [ 6  7]]

 [[21 22]
  [26 27]]]
The elements in ths last rows are :
[[16 17 18 19 20]
 [36 37 38 39 40]
 [56 57 58 59 60]]
the every other element is:
[[[ 1  3  5]
  [ 6  8 10]
  [11 13 15]
  [16 18 20]]

 [[21 23 25]
  [26 28 30]
  [31 33 35]
  [36 38 40]]

 [[41 43 45]
  [46 48 50]
  [51 53 55]
  [56 58 60]]]


In [28]:
#doing power outputs


arr = np.array([1, 2, 3, 4, 5])
print("Squared:", arr ** 2)
print("Cubed:", arr ** 3)

print("Quatro:" , arr ** 4)

Squared: [ 1  4  9 16 25]
Cubed: [  1   8  27  64 125]


In [36]:
#boolean indexing

a = np.array([1,2,3,67,45,8])
filtered = a[a > 3]
print(filtered)

#printing even numebers
even_num = a[a % 2 == 0]
print(even_num)


#printing odd numbers
odd_numbers = a [ a % 2 != 0]
print(odd_numbers)


array = a[(a>1)  & (a<67)]
print(array)

[67 45  8]
[2 8]
[ 1  3 67 45]
[ 2  3 45  8]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

# This works:
reshaped = arr.reshape(2, 3)
print("2x3:", reshaped)

# This fails - try it and see the error:
# bad_reshape = arr.reshape(2, 4)  # 2*4=8 but arr has 6 elements!

import numpy as np

x = np.array([[1,2,3],[4,5,6]])  # Shape: (2, 3)
w = np.array([4,5])               # Shape: (2,)

# Reshape w to be a column vector (2, 1)
w_reshaped = np.reshape(w, (2, 1))

# Now broadcast and add
result = x + w_reshaped

print("x shape:", x.shape)              # (2, 3)
print("w_reshaped shape:", w_reshaped.shape)  # (2, 1)
print("Result:")
print(result)


# **Output:**

# x shape: (2, 3)
# w_reshaped shape: (2, 1)
# Result:
# [[5 6 7]
#  [9 10 11]]
# ```

# **What happened:**
# ```
# x = [[1, 2, 3],     w = [[4],     Result = [[5,  6,  7],
#      [4, 5, 6]]          [5]]               [9, 10, 11]]

# w broadcasts to:    [[4, 4, 4],
#                      [5, 5, 5]]

2x3: [[1 2 3]
 [4 5 6]]
x shape: (2, 3)
w_reshaped shape: (2, 1)
Result:
[[ 5  6  7]
 [ 9 10 11]]
