In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
import tensorflow as tf
import numpy as np

scalar = tf.constant(7)
vector = tf.constant([2,3])
matrix = tf.constant([[1,2,3], [4,5,6,]])
array_3d = tf.constant([[[1,2,3],[4,5,6]]
                       ,[[2,3,4,],[5,6,7]]])

#printing the shape of scaler will result in ()
print(scalar.shape)
# #printing the shape of matrix
print(matrix.shape)
# #printing the shape of 3d array
print(array_3d.shape)

#now we are going to print the type of tensors
print(scalar.dtype)
print(vector.dtype)
print(matrix.dtype)
print(array_3d.dtype)
#the answer would be "int32"

<dtype: 'int32'>
<dtype: 'int32'>
<dtype: 'int32'>
<dtype: 'int32'>


In [ ]:
#now we are going to print the dimensions of each exampple we have taken of tensors
#we can use the arrays/tensors made in the previos cell
#also we dont have to import tensorflow and numpy again

print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(array_3d.ndim)
#we have made the tensors of 3 dimensions yet , in the next cell we are going
#make tensors of 4 dimensions


0
1
2
3


In [ ]:
#we are going to make 4 dimensions tensors now
element = np.random.rand(32,224,224,3)
print(element.shape)

(32, 224, 224, 3)


In [ ]:
# Create empty 4D tensor
tensor_4d = np.zeros((5, 128, 128, 1))
print(f"Shape: {tensor_4d.shape}")
# Output: Shape: (5, 128, 128, 1)
#         5 grayscale images, 128x128 pixels

In [ ]:
# If you have 3 images (example)
image1 = np.random.rand(100, 100, 3)  # Single image
image2 = np.random.rand(100, 100, 3)
image3 = np.random.rand(100, 100, 3)

# Stack them into 4D tensor
batch = np.stack([image1,image2,image3])
print(f"shape: {batch.shape}")



shape: (3, 100, 100, 3)


 Accessing Elements in 4D Tensor


In [ ]:
#making a 4D tensor
tensor = np.random.rand(2,3,3,2)




#accesing first image only
print(tensor[0]) # because we only need the first image

#accessing the first pixel
print(tensor[0,0,0]) #first pixel of first image

#accesing only red channel
print(tensor[0,:, :, 0])

#accessing the second image's blue channel
print(tensor[1,:,:,1])



[[[0.78658906 0.55140162]
  [0.37921171 0.69994081]
  [0.75106006 0.59646659]]

 [[0.18403388 0.2793714 ]
  [0.17410989 0.88808489]
  [0.56668178 0.23184078]]

 [[0.7127089  0.252723  ]
  [0.91509975 0.70640474]
  [0.53768807 0.35951753]]]
[0.78658906 0.55140162]
[[0.78658906 0.37921171 0.75106006]
 [0.18403388 0.17410989 0.56668178]
 [0.7127089  0.91509975 0.53768807]]
[[0.76273982 0.42008261 0.53919433]
 [0.6183086  0.65492895 0.79181122]
 [0.22532249 0.03492538 0.93105858]]


Common 4D Tensor Formats

In [ ]:
# #most common imagess

#   (batch_size, height, width, channels)
# Example: (32, 224, 224, 3)
# - 32 images
# - 224x224 pixels each
# - RGB (3 channels)


# #videoss formatt
# (batch_size, frames, height, width)
# Example: (8, 30, 64, 64)
# - 8 videos
# - 30 frames per video
# - 64x64 pixels per frame



# #time seriesss format
# (batch_size, time_steps, features, channels)
# Example: (16, 100, 10, 1)
# # - 16 sequences
# # - 100 time steps
# # - 10 features
# - 1 channel

In [ ]:

import numpy as np
import tensorflow as tf


np_array = np.array([[1,2],[3,4]])

tensor_flow = tf.constant([[1,2],[4,5]])

print(type(np_array))
print(type(tensor_flow))


#we do the conversion here fron tensor to numpy an dnumpy to tensor
tensor_from_numpy = tf.constant(np_array)
numpy_from_tensor = tensor_flow.numpy()
print(type(tensor_from_numpy))
print(type(numpy_from_tensor))




#now we are going to do the excercise
#aatep one to make a numpyarray
array = np.array([[1,2],[3,4]])
numpy_to_tensor = tf.constant(array)
array_2 = np.array([array ** 5])

#convert back into tensor flow
tensor_to_numpy = numpy_to_tensor.numpy()

print(f"the original array is: {array}")
print(f"the Converted array is: {numpy_to_tensor}")
print(f"the Multiplication with 5 results in : {array_2}")
print(f"again converted to tensor is: {tensor_to_numpy}")
#one mistake i made here is that i used the .numpy() method with array_2
#array_2 is a numpy array and it does not have a .numpy method
#we make the numpy_to_tensor is a tensor , conveted by .numpy()



<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.ndarray'>
the original array is: [[1 2]
 [3 4]]
the Converted array is: [[1 2]
 [3 4]]
the Multiplication with 5 results in : [[[   1   32]
  [ 243 1024]]]
again converted to tensor is: [[1 2]
 [3 4]]


In [ ]:
# Element-wise operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Addition:", tf.add(a, b))  # or just a + b
print("Multiplication:", tf.multiply(a, b))  # element-wise
print("Matrix multiplication:", tf.matmul(a, b))  # THIS IS DIFFERENT!


# YOUR TASK:
# 1. What's the difference between tf.multiply and tf.matmul?
# 2. Try both and compare outputs
# 3. When would you use each one in neural networks?

# Hint: Neural networks use matrix multiplication constantly!

#example for tf.multiply
     [[1, 2],      [[5, 6],      [[1×5, 2×6],      [[5, 12],
     [3, 4]]   ×   [7, 8]]   =   [3×7, 4×8]]   =   [21, 32]]
     
Same position elements multiply together!
Position (0,0): 1 × 5 = 5
Position (0,1): 2 × 6 = 12
Position (1,0): 3 × 7 = 21
Position (1,1): 4 × 8 = 32



#example for tf.matmultiply
[[1, 2],      [[5, 6],      
     [3, 4]]   @   [7, 8]]   
     
Row × Column operations:
(0,0): 1×5 + 2×7 = 19
(0,1): 1×6 + 2×8 = 22
(1,0): 3×5 + 4×7 = 43
(1,1): 3×6 + 4×8 = 50

Result: [[19, 22],
         [43, 50]]

In [ ]:
import tensorflow as tf
import numpy as np

# Create two matrices
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

element_wise = tf.multiply(a, b)
print(element_wise.numpy())

matrix_mult = tf.matmul(a, b)
print(matrix_mult.numpy())


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


#tf.multiply (Element-wise) - Use for:

Attention Mechanisms

Dropout / Masking

Gating Mechanisms (LSTM, GRU)


In [ ]:
########ATTENTION MECHANISM#######

# Scale certain features
attention_weights = tf.constant([[0.8, 0.2], [0.3, 0.7]])
features = tf.constant([[10, 20], [30, 40]])
weighted_features = tf.multiply(attention_weights, features)
# Result: [[8, 4], [9, 28]] - scaled by attention


#######DROPOUT/MASKINGG########
# Randomly drop neurons
dropout_mask = tf.constant([[1, 0], [1, 1]], dtype=tf.float32)
activations = tf.constant([[5.0, 3.0], [2.0, 4.0]])
dropped = tf.multiply(activations, dropout_mask)
# Result: [[5, 0], [2, 4]] - some neurons zeroed out

LSTM and GRU = Neural networks with MEMORY
They can remember things from the past while learning new things!

📖 Why Do We Need Memory?
Problem with Regular Neural Networks:
Imagine reading a sentence word by word:
"The cat sat on the ___"
To fill in the blank, you need to REMEMBER:

✅ There's a "cat" (from earlier)
✅ The word "on" suggests a place

Regular neural networks FORGET earlier words!

💡 Real Life Example:
You (Human with Memory):
Word 1: "The"     → Remember: article
Word 2: "cat"     → Remember: animal, subject
Word 3: "sat"     → Remember: past action
Word 4: "on"      → Remember: preposition
Word 5: "the"     → Remember: another article
Word 6: ???       → You know: "mat" or "floor" (because you remember CAT + SAT + ON)
Regular Neural Network (No Memory):
Word 1: "The"     → Process... forget
Word 2: "cat"     → Process... forget
Word 3: "sat"     → Process... forget
Word 4: "on"      → Process... forget
Word 5: "the"     → Process... forget
Word 6: ???       → "Uh... I forgot what we were talking about"
LSTM/GRU = Networks that REMEMBER!

🔄 What Are They Used For?
1. Language (Text)

Translation: "Hello" → "Hola"
Chatbots: Remember conversation
Text generation: Write stories

2. Time Series

Stock prices: Remember trends
Weather prediction: Remember patterns
Sales forecasting

3. Speech & Audio

Speech recognition: "Hey Siri"
Music generation

4. Video

Action recognition: What's happening?
Video captioning

Basically: ANYTHING that happens over TIME!

LSTM (Long Short-Term Memory)
Think of LSTM as a SMART NOTEBOOK with 3 DECISIONS:

│      📓 LSTM Memory Cell            
│                                   
│  🚪 Gate 1: FORGET GATE           
│     "Should I erase old notes?"     
│                                    
│  🚪 Gate 2: INPUT GATE             
│     "Should I write new notes?"     
│                                     
│  🚪 Gate 3: OUTPUT GATE            
│     "Should I share my notes?"      

Example: Reading a Story
Sentence: "John went to Paris. He loved the city."

Processing "John":
 Forget Gate: "Don't forget anything yet" (keep = 1.0)
Input Gate:  "Remember: main character is John" (write = 0.9)Output Gate: "Yes, output this info" (show = 0.8)

Processing "Paris":
 Forget Gate: "Keep John in memory" (keep = 0.9)
 Input Gate:  "Remember: location is Paris" (write = 0.9)
 Output Gate: "Output location info" (show = 0.7)

Processing "He":
 Forget Gate: "Keep John (main character)" (keep = 1.0)
 Input Gate:  "He = John (already know)" (write = 0.1)
 Output Gate: "Connect 'He' to 'John'" (show = 0.9)
       ↑
    Remembers "John" from earlier!

🎯 LSTM Structure (Simple View)
python# Imagine each gate as a percentage (0-1)

# === STEP 1: FORGET GATE ===
"What should I forget from memory?"
forget_gate = 0.8  # Keep 80%, forget 20%
old_memory = old_memory × 0.8

# === STEP 2: INPUT GATE ===
"What new information should I remember?"
input_gate = 0.6   # Remember 60% of new info
new_info = current_input × 0.6
memory = old_memory + new_info

# === STEP 3: OUTPUT GATE ===
"What should I output?"
output_gate = 0.9  # Show 90% of memory
output = memory × 0.9

GRU (Gated Recurrent Unit)
Think of GRU as a SIMPLER LSTM:

│      📝 GRU Memory Cell             
│                                     
│  🚪 Gate 1: UPDATE GATE            
│     "How much should I update?"    
│                                    
│  🚪 Gate 2: RESET GATE             
│     "Should I forget the past?"     
│                                     
│  (Simpler = Faster = Popular!)      

GRU = LSTM with fewer gates (2 instead of 3)

In [ ]:
############################LSTM###############
import tensorflow as tf

# Create LSTM layer
model = tf.keras.Sequential([
    # Input: sequences of 100 time steps, each with 10 features
    tf.keras.layers.LSTM(64, input_shape=(100, 10)),
    #                    ↑
    #              64 memory cells

    # Output layer
    tf.keras.layers.Dense(1)
])

# Example: Predict next word
# Input: "The cat sat on"
# LSTM remembers: cat, sat, on
# Output: "the" (mat/floor likely next)


##################GRU#################
# Same thing, but with GRU
model = tf.keras.Sequential([
    tf.keras.layers.GRU(64, input_shape=(100, 10)),
    #                   ↑
    #           Simpler, faster than LSTM

    tf.keras.layers.Dense(1)
])




** ##matmul (Matrix Multiplication) - Use for**

 Dense/Fully Connected Layers

 Batch Processing

 Convolutional Layers (Behind the scenes)

In [ ]:

###DENSE OR FULLY CONNECTED LAYERSS#######

# This is THE CORE of neural networks!
inputs = tf.constant([[1.0, 2.0, 3.0]])  # Input features (1, 3)
weights = tf.constant([
    [0.1, 0.2],  # Weight for neuron 1
    [0.3, 0.4],  # Weight for neuron 2
    [0.5, 0.6]   # Weight for neuron 3
])  # Shape: (3, 2) - transforms 3 features to 2 neurons

output = tf.matmul(inputs, weights)  # (1, 3) @ (3, 2) = (1, 2)
# Result: [[2.2, 2.8]] - activations of 2 neurons



####BATCH PROCESSING####

# Process multiple samples at once
batch_inputs = tf.constant([
    [1.0, 2.0],  # Sample 1
    [3.0, 4.0],  # Sample 2
    [5.0, 6.0]   # Sample 3
])  # Shape: (3, 2) - 3 samples, 2 features

weights = tf.constant([
    [0.5, 0.3, 0.2],  # 3 neurons
    [0.1, 0.4, 0.7]
])  # Shape: (2, 3)

outputs = tf.matmul(batch_inputs, weights)  # (3, 2) @ (2, 3) = (3, 3)
# Each of 3 samples gets transformed to 3 neuron outputs




# CNNs use matrix multiplication for efficient convolution
# Flattened patches × filters = feature maps

You have 3 numbers: [1.0, 2.0, 3.0]
You want to get 2 neurons (neuron 1 and neuron 2)

NEURON 1 (first column of weights):
= 1.0×0.1 + 2.0×0.3 + 3.0×0.5
= 0.1 + 0.6 + 1.5
= 2.2 ✅

NEURON 2 (second column of weights):
= 1.0×0.2 + 2.0×0.4 + 3.0×0.6
= 0.2 + 0.8 + 1.8
= 2.8 ✅

Output: [2.2, 2.8]






####BATCH PROCESSING

batch_inputs = [[1.0, 2.0],  # Person 1
                [3.0, 4.0],  # Person 2
                [5.0, 6.0]]  # Person 3

weights = [[0.5, 0.3, 0.2],  # Transform into 3 neurons
           [0.1, 0.4, 0.7]]

outputs = batch_inputs @ weights



PERSON 1: [1.0, 2.0 Neuron 2: 1.0×0.3 + 2.0×0.4] = 0.3 + 0.8 = 1.1

 Neuron 1: 1.0×0.5 + 2.0×0.1 = 0.5 + 0.2 = 0.7

Neuron 3: 1.0×0.2 + 2.0×0.7 = 0.2 + 1.4 = 1.6


PERSON 2: [3.0, 4.0]

Neuron 1: 3.0×0.5 + 4.0×0.1 = 1.5 + 0.4 = 1.9

 Neuron 2: 3.0×0.3 + 4.0×0.4 = 0.9 + 1.6 = 2.5

 Neuron 3: 3.0×0.2 + 4.0×0.7 = 0.6 + 2.8 = 3.4


PERSON 3: [5.0, 6.0]

Neuron 1: 5.0×0.5 + 6.0×0.1 = 2.5 + 0.6 = 3.1

 Neuron 2: 5.0×0.3 + 6.0×0.4 = 1.5 + 2.4 = 3.9

 Neuron 3: 5.0×0.2 + 6.0×0.7 = 1.0 + 4.2 = 5.2


Output:

[[0.7, 1.1, 1.6],   ← Person 1's results

 [1.9, 2.5, 3.4],   ← Person 2's results

 [3.1, 3.9, 5.2]]   ← Person 3's results

In [ ]:
# This is CRUCIAL for neural networks
tensor = tf.constant([[1, 2, 3, 4, 5, 6]])
print("Original shape:", tensor.shape)  # (1, 6)

# Reshape to different dimensions
reshaped_2x3 = tf.reshape(tensor, (2, 3))
reshaped_3x2 = tf.reshape(tensor, (3, 2))
reshaped_6x1 = tf.reshape(tensor, (6, 1))

print("2x3:", reshaped_2x3)
print("3x2:", reshaped_3x2)
print("6x1:", reshaped_6x1)

# YOUR TASKS:
# 1. Create a tensor of shape (4, 4) with values 1-16
# 2. Reshape it to (2, 8)
# 3. Reshape it to (8, 2)
# 4. Try to reshape to (3, 5) - what happens? Why?
# 5. Use tf.reshape with -1: tf.reshape(tensor, (2, -1))
#    What does -1 do? (This is a powerful trick!)

In [ ]:
import tensorflow as tf

# Create 16 numbers arranged in 4×4
tensor = tf.constant([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print("Original (4×4):")
print(tensor.numpy()) #converting into a numpy array by using .numpy( method)
print("Shape:", tensor.shape)  # (4, 4)



#####reshaping into 2x8  ####
reshaped_2x8 = tf.reshape(tensor, (2, 8))
print("Reshaped to 2×8:")
print(reshaped_2x8.numpy())

#reshaped to 8x2 ######
reshaped_8x2 = tf.reshape(tensor, (8, 2))
print("Reshaped to 8×2:")
print(reshaped_8x2.numpy())




###reshaping in 3x5 ########
try:
    reshaped_3x5 = tf.reshape(tensor, (3, 5))
except Exception as e:
    print("\n❌ ERROR!")
    print("Why? 3×5 = 15, but we have 16 elements!")
    print("Can't fit 16 numbers into 15 spaces!")


# Let TensorFlow calculate one dimension automatically!
reshaped_auto = tf.reshape(tensor, (2, -1))
#                                   "You figure this out!"

print("\nUsing -1 (auto-calculate):")
print("Shape:", reshaped_auto.shape)  # (2, 8)
print(reshaped_auto.numpy())


                           # You say: "I want ? rows, 2 columns"
result = tf.reshape(tensor, (-1, 2))
# TensorFlow: "6 ÷ 2 = 3 rows"
# Result: (3, 2)

print(result.numpy())
# [[1, 2],
#  [3, 4],
#  [5, 6]]


Original (4×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Reshaped to 2×8:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped to 8×2:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

❌ ERROR!
Why? 3×5 = 15, but we have 16 elements!
Can't fit 16 numbers into 15 spaces!

Using -1 (auto-calculate):
Shape: (2, 8)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
##the uses of Reshaping in tensor flow
#####image processing#######

# Image comes in: (height, width, channels)
image = tf.random.normal((28, 28, 1))  # 28×28 grayscale image

# Flatten for Dense layer
flattened = tf.reshape(image, (1, -1))  # (1, 784)
# Now it's: 1 sample with 784 features!

# Can feed to neural network
# Dense layer expects: (batch_size, features)


#####Batch processing#######
# Have 100 images
images = tf.random.normal((100, 28, 28, 1))

# Reshape each image to 784 features
reshaped = tf.reshape(images, (100, -1))  # (100, 784)
# Now: 100 samples, each with 784 features

In [ ]:
# UNDERSTANDING COMPUTATIONAL GRAPHS_______________________

# TensorFlow builds a graph of operations
x = tf.constant(3.0)
y = tf.constant(4.0)
z = x + y

print("Result:", z)

# The graph: x --> [+] <-- y --> z
# This allows TensorFlow to:
# 1. Optimize the computation
# 2. Calculate gradients automatically (for backpropagation)
# 3. Run on GPUs efficiently

# YOUR TASK:
# Build a computational graph for this equation:
# result = (a * b) + (c / d) - e
# Where a=2, b=3, c=10, d=2, e=1
# Print the result
# Think: What operations are happening in what order?

Result: tf.Tensor(7.0, shape=(), dtype=float32)


In [ ]:
#A computational graph = A recipe showing step-by-step calculations
#Think of it like a flowchart for math

import tensorflow as tf

# Step 1: Create inputs
x = tf.constant(3.0)
y = tf.constant(4.0)

# Step 2: Build the graph (define operations)
z = x + y

# Step 3: Result
print("Result:", z.numpy())  # 7.0



#####task1
# Step 1: Define all inputs
a = tf.constant(2.0)
b = tf.constant(3.0)
c = tf.constant(10.0)
d = tf.constant(2.0)
e = tf.constant(1.0)

# Step 2: Build the graph (break down the equation)
multiply = a * b      # 2 * 3 = 6
divide = c / d        # 10 / 2 = 5
add = multiply + divide   # 6 + 5 = 11
result = add - e      # 11 - 1 = 10

# Step 3: Print result
print("Result:", result.numpy())  # 10.0

# Alternative: Do it in one line (same graph!)
result_oneline = (a * b) + (c / d) - e
print("One-line result:", result_oneline.numpy())  # 10.0




# a (2) ──┐
#             ├──→ [×] ──→ multiply (6) ──┐
#     b (3) ──┘                           │
#                                         ├──→ [+] ──→ add (11) ──┐
#     c (10) ─┐                           │                        │
#             ├──→ [÷] ──→ divide (5) ────┘                        │
#     d (2) ──┘                                                    ├──→ [-] ──→ result (10)
#                                                                  │
#     e (1) ───────────────────────────────────────────────────────┘




# Step 1: multiply = a × b = 2 × 3 = 6
# Step 2: divide = c ÷ d = 10 ÷ 2 = 5
# Step 3: add = multiply + divide = 6 + 5 = 11
# Step 4: result = add - e = 11 - 1 = 10

# Final Answer: 10 ✅


In [ ]:
######MORE COMPLEX EXAMPLE#####

import tensorflow as tf

x = tf.constant(5.0)
y = tf.constant(3.0)

# Build the graph step by step
x_squared = x * x           # 25
y_squared = y * y           # 9
numerator = x_squared + y_squared  # 34
denominator = x - y         # 2
result = numerator / denominator   # 17

print("Result:", result.numpy())  # 17.0

1. Optimization
TensorFlow can rearrange operations for speed:
python# You write:
result = (a * b) + (a * c)

# TensorFlow optimizes to:
result = a * (b + c)  # Fewer operations!

2. Automatic Gradients (Backpropagation)

python# TensorFlow tracks how to calculate derivatives

x = tf.Variable(3.0)


with tf.GradientTape() as tape:

    y = x * x  # y = x²

    
gradient = tape.gradient(y, x)  # dy/dx = 2x = 6

print("Gradient:", gradient.numpy())  # 6.0



# The graph knows: "y depends on x, so I can calculate dy/dx"

3. GPU Acceleration


TensorFlow can run the whole graph on GPU automatically

# No need to move data back and forth!

